### PR TITLE
dev: fix: rm folders with sudo privileges

### PR DESCRIPTION
**Pull request by marcello33**
# Description

This PR fixes behaviour of `rm -rf` by running it with sudo privileges.
Also, it updates the snapshots URLs of bor and heimdall

# Changes

- [x] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)
- [ ] New test case for remote devnet

# Checklist

- [x] I have added at least 2 reviewer or the whole pos-v1 team
- [x] I have added sufficient documentation in code
- [x] I will be resolving comments - if any - by pushing each fix in a separate commit and linking the commit hash in the comment reply

## Testing

- [x] I have tested this code manually on local environment
- [x] I have tested this code manually on remote devnet using express-cli
- [ ] I have tested this code manually on mumbai

### CODE REVIEW

**Review by pratikspatil024 — APPROVED** [review]
Just curious to know, where are we using the newly added env variables like `SHADOW_CHAIN_ID`, `HEIMDALL_SEEDS`, `NETWORK`, etc.

**Review by Raneet10 — APPROVED** [review]

**Comment by Raneet10** [comment]
> Just curious to know, where are we using the newly added env variables like `SHADOW_CHAIN_ID`, `HEIMDALL_SEEDS`, `NETWORK`, etc.

Yeah these are added in #157 for the purpose of setting up mumbai/mainnet nodes.

**Comment by Raneet10** [comment]
Actually @marcello33 , will it makes more sense to update the example config changes in #157 ?

**Review by 0xsharma — APPROVED** [review]

**Comment by marcello33** [comment]
> Actually @marcello33 , will it makes more sense to update the example config changes in #157 ?

Agreed @Raneet10 
Moved such changes to your PR and left this only for the privileges on `rm -rf` which was failing

**Comment by marcello33** [comment]
> Actually @marcello33 , will it makes more sense to update the example config changes in #157 ?

Agreed @Raneet10 
Moved such changes to your PR and left this only for the privileges on `rm -rf` which was failing

> Just curious to know, where are we using the newly added env variables like `SHADOW_CHAIN_ID`, `HEIMDALL_SEEDS`, `NETWORK`, etc.

Thanks @pratikspatil024 
Moved the changes to the original PR

**Pull request merged**
